### ISSUE TITLE
Sanity v4 styling issues

### ISSUE THREAD

**Issue by Camorte** [sanity-io/sanity#10096]
Hello! I have setup a Sanity v3.5.7 project a while back and decided to migrate over to v4 as I wanted to implement `next-sanity` presentation tool/visual editing. I followed this guide: https://www.sanity.io/docs/help/v3-to-v4

Everything was looking good until I ran `sanity deploy` and saw that all of the popovers in production is missing their heights (see screenshots). And when I built and started it locally, then I saw that the issue was the same there. It feels like I am missing a step somewhere and I have tried to remove packages and going back to different versions as well, but it lead to nowhere. 

I tried to migrate over everything, but I am not sure if this is an overall bug or I am missing something completely, would love to get some help on the issue.

<img width="728" height="165" alt="Image" src="https://github.com/user-attachments/assets/9bdd5333-4df9-4190-82c1-99ee3a96cb7d" />

<img width="703" height="228" alt="Image" src="https://github.com/user-attachments/assets/78bb1a46-953a-4589-8aba-4a31fa8f965a" />

This is my `package.json`:

```
{
  "name": <project name>,
  "private": true,
  "version": "1.0.0",
  "main": "package.json",
  "license": "UNLICENSED",
  "scripts": {
    "dev": "sanity dev",
    "start": "sanity start",
    "build": "sanity build",
    "deploy": "sanity deploy",
    "deploy-graphql": "sanity graphql deploy"
  },
  "keywords": [
    "sanity"
  ],
  "dependencies": {
    "@sanity/color-input": "4.0.5",
    "@sanity/orderable-document-list": "1.4.0",
    "@sanity/vision": "4.1.1",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "sanity": "4.1.1",
    "styled-components": "6.1.19"
  },
  "devDependencies": {
    "@sanity/eslint-config-studio": "5.0.2",
    "@types/react": "18.3.23",
    "eslint": "^8.6.0",
    "prettier": "^3.0.2",
    "typescript": "^5.1.6"
  },
  "prettier": {
    "semi": false,
    "printWidth": 100,
    "bracketSpacing": false,
    "singleQuote": true
  }
}
```

I am using the structure tool to customise Sanity studio in `sanity.config.ts`, which looks like this:

```
import {defineConfig} from 'sanity'
import {structureTool} from 'sanity/structure'
import {visionTool} from '@sanity/vision'
import {schemaTypes} from './schemaTypes'
import structure from './structure'
import {colorInput} from '@sanity/color-input'
import {presentationTool} from 'sanity/presentation'
import {resolve} from './resolve'

export default defineConfig({
  name: 'default',
  title: 'lokaltheatret',

  projectId: 'c99u49i1',
  dataset: 'production',

  scheduledPublishing: {
    enabled: false,
  },

  plugins: [
    presentationTool({
      allowOrigins: ['http://localhost:*', 'https://lokaltheatret.no'],
      previewUrl: {
        initial: process.env.SANITY_STUDIO_PREVIEW_ORIGIN,
        previewMode: {
          enable: '/api/draft-mode/enable',
        },
      },
      resolve,
    }),
    colorInput(),
    structureTool({
      structure,
    }),
    visionTool(),
  ],

  schema: {
    types: schemaTypes,
  },
})
```

**Comment by tylermcrobert** [comment]
I'm also having this issue, my version was on a later version of the v3, and upgrading to v4 did not help, nor does downgrading.

I sincerely hope this issue is prioritized, it is getting in the way of any editing.

**Comment by JackP96** [comment]
Also having this issue. Hosting on Vercel with node.js 20 in both local and host environments. Everything looks good/works locally, but then I get this height issue in the live site.

**Comment by FabianMorenoSyntax** [comment]
Same here, even when starting a fresh project following the quick start as described in the documentation. Works well locally but doesn't display popovers correctly. Additionally, the font isn't loading correctly (wrong weight)

**Comment by ryanrapp** [comment]
Yes I have the same issue with it only appearing on vercel/sanity.studio, and not appearing locally.
I was able to fix it on vercel/sanity.studio by adding a custom.css

```
// custom.css
  [data-ui="Popover__wrapper"], [data-ui="Popover__wrapper"] > div {
    flex-basis: fit-content !important;
    flex: 1 1 !important;
  }
```

```
// sanity.config.ts
import "./custom.css";
```

The framework's "flex: 1 1 1px" is causing the popovers to be exactly 1px tall.

**Comment by palockocz** [comment]
I have the same problem. As it says in the last post. Locally `pnpm run dev` everything works, but as soon as I build the project using `pnpm run build` and run it, either locally or in production, the stylesheet problem occurs.

I tried to downgrade the dependencies in package.json, but to no success. The problem occurred when I deleted an unrelated package and all dependencies in `pnpm-lock.yml` were updated automatically according to the ranges given.

The broken stylesheets prevented Sanity Studio from being used in production.

On one project I was able to fix it by pulling an older version of `pnpm-lock.yml` from GIT, but on another project I was converting from bun to pnpm I no longer had that option.

I'm attaching screenshots of what the broken styles look like.

<details><summary>Details</summary>
<p>
<img width="605" height="529" alt="Image" src="https://github.com/user-attachments/assets/ce886118-8e84-4c57-937f-32c6ce026115" /><img width="741" height="255" alt="Image" src="https://github.com/user-attachments/assets/cc9e676f-e303-4e5a-974e-217574115721" />
</p>
</details> 

**Additional info:**
I have installed Sanity package `v3.99.0` and Sanity/ui `v3.0.1`. (the problem must be in some sub-dependency)
I am using Astro framework with React.

**Comment by EoinFalconer** [comment]
Hi all 👋 Thank you for your reports both here and in Discord. We are actively looking into this issue and will report back when we have a resolution!

**Comment by p-mylecharane** [comment]
Bumping this! My clients are going nuts 🥜

**Comment by EoinFalconer** [comment]
Resolution has been found! There was a downstream dependency update where rollup went from 4.45.3 to 4.46.0 which has caused the issue. We are preparing a patch release which will pin rollup to 4.45.3 in [pkg-utils](https://github.com/sanity-io/pkg-utils). In the meantime, you can add an override for rollup. For pnpm that would be the following following:

```
 "pnpm": {
    "overrides": {
      "rollup": "4.45.3"
    }
  },
```

Thank you again for the reports. I will leave this issue open and close once the release is out 😊

**Comment by bjoerge** [comment]
Simply pinning the rollup version in your studio's `devDependencies` should fix it too:

```json
"devDependencies": {
  "rollup": "4.45.3"
}
```

**Comment by EoinFalconer** [comment]
Fix released in [v4.2.0](https://github.com/sanity-io/sanity/releases/tag/v4.2.0), please refer to [this](https://www.sanity.io/docs/changelog/7dd374d4-1037-4f42-bad5-7ee7d53ee935#a6d73a4dacab) if you are running into issues! Thanks for the help and reports!

**Comment by palockocz** [comment]
Not working for me. I updated sanity to `v4.2.0`, added rollup `v4.45.3` to devDependencies, but no luck.

**EDIT: the approach using pnpm overrides is working.**

**Comment by Chivas1717** [comment]
It just worked for me. Since I am using yarn, i had to use this syntax instead of overrides inside of my package.json:
```
"resolutions": {
  "rollup": "4.45.3"
},
```

**Comment by tamjankowska** [comment]
I have upgraded sanity studio and rollup and also used the pnpm override for rollup.

I'm still seeing this issue. Locally, everything is great, but in my deployed studio the problem persists.

Is there anything else I can do? This is preventing my colleagues from completing their tasks.
