### ISSUE TITLE
Block editor "list" forces text after the list items to also become a list item

### ISSUE THREAD

**Issue by emanualjade** [sanity-io/sanity#10928]
**Describe the bug**
In the block editor, when you create list items it won't let you escape from list mode. It forces the next paragraph after the list items to automatically become a list item as well. 

**To Reproduce**
1. In your block editor click bulleted list icon or the numbered list icon. 
2. Create a couple list items of random text.
3. Hit enter to go to the next list item but don't type any text.
4. Hit the delete key to try and get out of list mode.
5. Try to type a paragraph. 

You'll notice the paragraph automatically becomes a list item

**Expected behavior**
You would expect the paragraph to remain as a paragraph.

**Screenshots**

See the video of this bug
https://monosnap.ai/file/47OKlkwkSregjgweWF2qRn0vCoaEdw

**Which versions of Sanity are you using?**
@sanity/cli (global)          4.11.0 (up to date)
@sanity/cli                   4.11.0 (up to date)
@sanity/eslint-config-studio   5.0.2 (up to date)
@sanity/icons                  3.7.4 (up to date)
@sanity/rich-date-input        3.0.6 (up to date)
@sanity/table                  2.0.0 (up to date)
@sanity/vision                4.11.0 (up to date)
sanity                        4.11.0 (up to date)

**What operating system are you using?**
Running on a mac Tahoe 26.0.1

**Which versions of Node.js / npm are you running?**
11.6.0
v24.9.0

**Comment by christianhg** [comment]
Hi there! Sorry about that! 

Looks like there is a regression in [v2.15.2](https://github.com/portabletext/editor/releases/tag/%40portabletext%2Feditor%402.15.2) of `@portabletext/editor` that could cause this problem.

I've now cut a [v2.15.3](https://github.com/portabletext/editor/releases/tag/%40portabletext%2Feditor%402.15.3) that should resolve the issue. Could you try reinstalling Studio or upgrading `@portabletext/editor` manually?

Thank you!

**Comment by emanualjade** [comment]
Thanks for the ultra-quick response. It's working well now. 

At this time the latest version of sanity `v4.11.0`, or a related package, still references the old `v2.15.2` of `@portabletext/editor` so reinstalling sanity didn't solve it for me. 

**What I did to get your fix:**

Since I'm using npm I did this

1. Add this to my package.json in my studio
```js
"overrides": {
  "@portabletext/editor": "2.15.3"
}
```

2. Delete studio/package-lock.json and node_modules
3. Run `npm install` to reinstall with override

I'll eventually remove that overrides and just use whatever the main sanity package uses when it's up to date.

**Comment by christianhg** [comment]
> Thanks for the ultra-quick response. It's working well now.

Thank _you_ for reporting the issue!

> I'll eventually remove that overrides and just use whatever the main sanity package uses when it's up to date.

Awesome! Thank you!
