### ISSUE TITLE
"Review changes" pane is not showing diffs

### ISSUE THREAD

**Issue by good-idea** [sanity-io/sanity#7297]
**Describe the bug**

The "Review changes" pane shows menu items for document revisions, but the pane itself always shows "There are no changes".

**To Reproduce**

I'm not sure how to reproduce or debug this. See notes in additional context below. 

**Expected behavior**

Document revisions & diffs should show up in the pane.

**Screenshots**

<img width="590" alt="image" src="https://github.com/user-attachments/assets/7da6a29b-1da4-4e56-9935-ee3aac451191">

**Which versions of Sanity are you using?**

```
@sanity/cli (global)                   3.52.4 (up to date)
@sanity/color-input                     3.1.1 (up to date)
@sanity/dashboard                       4.0.0 (up to date)
@sanity/document-internationalization   3.0.0 (up to date)
@sanity/eslint-config-studio            4.0.0 (up to date)
@sanity/studio-secrets                  3.0.0 (up to date)
@sanity/vision                         3.52.4 (up to date)
sanity                                 3.52.4 (up to date)
```

**What operating system are you using?**

OS X

**Which versions of Node.js / npm are you running?**

Run `npm -v && node -v` in the terminal and copy-paste the result here.

```
9.8.1
v18.18.0
```

**Additional context**

- This is on our `production` dataset which is quite large. (25-30k documents). However, about 80% of those are synced from an external source and rarely get updated. The documents that are getting a lot of attention probably number in the dozens.
- Oddly, it works as expected on the `development` dataset - it also has nearly the same amount of documents, but is not edited as often.
- If I make an edit (and do not publish), that change does show up in the diff:
   <img width="1057" alt="image" src="https://github.com/user-attachments/assets/dad1d1bb-d822-4282-8057-8449a6664333">
   - It continues to appear with a refresh
   - It continues to appear after publishing and refreshing
- There is a network request to `https://<projectId>.api.sanity.io/v2024-05-28/data/doc/production/drafts.homepage,homepage?tag=sanity.studio.document.snapshots`, it returns one result
- There is a network request to `https://<projectId>.api.sanity.io/v2024-05-28/data/history/production/transactions/homepage,drafts.homepage?tag=sanity.studio.structure.history&effectFormat=mendoza&excludeContent=true&excludeMutations=true&includeIdentifiedDocumentsOnly=true&reverse=true&limit=50` that *DOES* include the recent change I made, and 49 other JSON objects with document revisions.

Because of this last note, I feel that the issue lies somewhere between that request and what is rendered - for some reason all of these seem to be filtered out at some point.

**Comment by fvieira** [comment]
This is nothing new, but the whole revision history hasn't been working great at all, and with the latest version v3.74.0, it seems to be even worse, to the point I can't even properly see what changed between the draft and the published version.

You can see a test below where I just changed a text from Blog to Articles, and then can't make head or tails of what Sanity is showing in the Revision History sidebar, with it not showing the text Blog anywhere (which is what the published version still has), and with the revision it shows having 4 Created entries after the first Published entry.

https://github.com/user-attachments/assets/31146d65-cb53-43f3-89fe-4b0b39c2a46e

**Comment by and-poulsen** [comment]
Any news on this?

**Comment by fvieira** [comment]
Still nothing, I'm dogfooding the latest versions of Sanity on our own backoffice, and "Review changes" is as broken as usual, as can be seen in this screenshot using `3.81.0` where I made a ton of changes since the last publish, and "Review changes" shows none.

![Image](https://github.com/user-attachments/assets/7558f8a0-5af6-4547-882c-d2af88ef25e7)

I love the new features Sanity keep throwing at us, but I just can't deliver them to our clients at the cost of losing the most basic feature of know what was changed between a live document and the current draft.

There's also plenty of people being affected by this, as can be seen in this thread:
https://sanity-io-land.slack.com/archives/C9Z7RC3V1/p1740098602728119

**Comment by ChrisNolan** [comment]
@pedrobonamin I believe this issue is likely connected to content releases 'breaking' some existing functionality.  Many of the editors out there rely on (and highly value (i.e. it is a 'selling point')) being able to see the 'history' of changes to a document and that seems to have 'gone away' the last few months.  Is it on your (or somebody's) radar to restore the functionality?  It is difficult when we have to decide between what features are essential and reverting to earlier studios to get one piece working, when we then loose access to other pieces that they've come to 'love'.

The slack thread @fvieira linked above has more details too.

**Comment by fvieira** [comment]
Done, just sent you the information you requested (and then some).

Thanks for looking into this!

**Comment by ttavni** [comment]
+1 for this. Some diff changes are showing - but not removals / strikethroughs in portable text!

**Comment by ChrisNolan** [comment]
I dm'd you an example (on the slack).  The API call I see in the browser isn't to /data/history but the fetch is using sanity::versionOf and that is erroring with
```
:

event: channelError
data: {"error":{"description":"Undefined function \"versionsOf\" in namespace \"sanity\"","type":"queryParseError"}}


event: disconnect
data: {"reason": "error"}
```

**Comment by danielsyvertsen** [comment]
We’re still affected by this issue in production, and it’s becoming quite critical for our clients! The “Review changes” pane is essential for transparency and editorial quality control — and it’s honestly a bit embarrassing to explain to clients that this core feature still doesn’t work properly.

I see the last update from the Sanity team was back in April. Could we please get a short update on whether this is being actively worked on or planned for a near release?

This one really impacts confidence in the platform — fixing it would make a big difference.

**Comment by fvieira** [comment]
Agree, I accompanied the progress on this task for a while through @pedrobonamin, and I'm happy there were large improvements a few months later, but the feature is still far from reliable even though it's one of the most critical ones for a CMS.

I do understand now how much more complicated the UX for this feature is, now that we have releases, because now the published version of a document can be updated not only through drafts, but also through releases, which means there is a difference between showing the history of a draft document and showing how it currently differs from the published version (maybe you updated the draft a couple days ago, but yesterday published a release, so the history of this draft doesn't include what is currently published).

A proper full featured diffing solution probably would require allowing us to compare any two versions regardless of them being drafts, published or releases, just like you can compare any two commits in git, and I hope that's what we are building towards, but until then, it is essential that we can at least quickly and reliably compare against the published version.

**Comment by pedrobonamin** [comment]
Hello @danielsyvertsen and @fvieira 👋🏻 

I'm sorry for the inconveniences, could you please share some details on what the issue is with the review changes? You can find me in the [community](https://snty.link/community) if you don't want to share it publicly.

I haven't seen any other reports since the last changes that were pushed in June.

Indeed, review changes is now more complicated because of the reasons @fvieira mentioned, `draft` and `published` were always two different documents for us, but shown as only one in the UI, now with the introduction of releases the change could be coming from a version document and not only from the draft, thats why we added details of where the change came from when you see the `published` version of the document using badges in the history entry.

<img width="600" height="650" alt="Image" src="https://github.com/user-attachments/assets/24b5072a-b44e-4ddf-8f85-9a9d54e329b6" />


We are also working on new diffing capabilities, one is inline diffing, you can [see the PR here ](https://github.com/sanity-io/sanity/pull/10792) which I think will be released this week or the next one, which shows the changes in the same field, for example:

<img width="640" height="107" alt="Image" src="https://github.com/user-attachments/assets/ccc2e55f-07a0-4c39-b536-8352ad52432d" />


We also have built in place for the initial release of releases, and have been improved over time, the compare versions view, which will let you compare two versions of the same document side by side. We are also working on further improvements here.

![Image](https://github.com/user-attachments/assets/c63dfcb2-2540-4f16-b262-e2e3b674d5d9)


We value this feature a lot and we know it is important for users, that's why we have been working on multiple updates since we released `releases` which was a fundamental change on the documents model to make it easier for users.

**Comment by fvieira** [comment]
Hi @pedrobonamin, at the moment I can't remember exactly what are the issues I've been having, much less each version of Sanity they happened in. At the time we were talking on Slack and the review changes interface was improved, I remember I reported to you quite a few issues remaining, but I never followed up on those, and since Slack history is no longer available I can't recover those issues.

So here's what I can do, first I'll wait for the inline diffing feature to be released (will it always diff with the Published version?), and then as soon as I have the time I will review both that feature and the Review changes. Also, I'll try to pay more attention and if I find any issues during usage, I'll try and reproduce in the more recent version and report if it happens there.

Thank you for the communication, it helps to see that Sanity is paying attention.

**Comment by pedrobonamin** [comment]
That will be super nice, thank you @fvieira ! 
Yes, in most of the cases it will be the published, but if you got two versions of the same document which are scheduled to be released, it will compare the second version to the version being released before.

Once again, thank you and hope to see you in Discord!

**Comment by pedrobonamin** [comment]
Hello everyone, multiple updates and bug fixes have landed to the review changes in the last year and we believe this is no longer an issue in the latest version of the studio.
If you think the issue persists please feel free to reopen it or open a new one so we can handle it accordingly.

Thank you!

**Comment by fvieira** [comment]
@pedrobonamin Fair enough, I haven't found the time to properly test this, so I'm not sure if the issues I've been having are fixed in the newest versions. If/when I can confirm a bug in the latest version, I'll let you know.

**Comment by fvieira** [comment]
Hi @pedrobonamin, as I thought, I still can't trust the Review Changes to properly compare the draft I'm seeing with the currently published version. I'm on the latest version, `5.13.0`, and while I ended up in the situation below through a somewhat contrived method, which was by having a custom publish action that edits the published version of the document, the issue is valid nonetheless, and I'm almost certain normal Sanity usage often leaves me in a similar state where I can't trust the Review Changes.

I hope the issue is clear from the screenshots below, but let me know if you need anything else.

**Published view, History tab**

<img width="1464" height="917" alt="Image" src="https://github.com/user-attachments/assets/60eb5fd0-2047-460a-a0a6-0205d5f9e050" />


---

**Draft view, History tab**

<img width="1463" height="914" alt="Image" src="https://github.com/user-attachments/assets/061ab947-b5f7-4827-ab9c-140b58cb1107" />


---

**Draft view, Review changes tab**

<img width="1465" height="913" alt="Image" src="https://github.com/user-attachments/assets/7b80b94d-83eb-4ff6-9092-14435a3c9f5b" />

**Comment by fvieira** [comment]
And now I've discarded the draft, and for some reason Review Changes decided to show me the difference between the published version (the wrong one still, but that's not even the issue now) and the discarded draft, which it apparently assumes is empty, so it just says that everything got deleted, which is false. The current state is that there is no draft, so I would expect Review Changes to simply say there are no changes, not this.  
 
<img width="1478" height="924" alt="Image" src="https://github.com/user-attachments/assets/d05b992b-8949-472a-bb0d-97d62c99361c" />

---

After I made a single change to the document, the review changes started actually being useful, although comically, it now says "Something went wrong". 😆 

(the screenshot has a second change too)
<img width="1471" height="918" alt="Image" src="https://github.com/user-attachments/assets/b0d20a5d-23eb-4c58-93f9-6035a6a727e6" />
